# Generated by Django 6.0.6 on 2026-06-30 19:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
        ('students', '0002_alter_student_options_alter_student_address_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-paid_date', '-created_at'], 'verbose_name': 'Payment', 'verbose_name_plural': 'Payments'},
        ),
        migrations.AlterModelOptions(
            name='paymenthistory',
            options={'ordering': ['-changed_at'], 'verbose_name': 'Payment history', 'verbose_name_plural': 'Payment histories'},
        ),
        migrations.AlterModelOptions(
            name='studentdebt',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Student debt', 'verbose_name_plural': 'Student debts'},
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Comment'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Discount'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='paid_date',
            field=models.DateField(verbose_name='Paid date'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('transfer', 'Transfer'), ('cheque', 'Cheque')], max_length=10, verbose_name='Payment method'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('paid', 'Paid'), ('pending', 'Pending'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='pending', max_length=10, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='students.student', verbose_name='Student'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='action',
            field=models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('deleted', 'Deleted')], max_length=10, verbose_name='Action'),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='changed_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Changed at'),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_changes', to=settings.AUTH_USER_MODEL, verbose_name='Changed by'),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='new_data',
            field=models.JSONField(blank=True, null=True, verbose_name='New data'),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='old_data',
            field=models.JSONField(blank=True, null=True, verbose_name='Old data'),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='payments.payment', verbose_name='Payment'),
        ),
        migrations.AlterField(
            model_name='studentdebt',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='debt', to='students.student', verbose_name='Student'),
        ),
        migrations.AlterField(
            model_name='studentdebt',
            name='total_fees',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total fees'),
        ),
        migrations.AlterField(
            model_name='studentdebt',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
    ]
