# Generated by Django 6.0.6 on 2026-06-30 19:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0001_initial'),
        ('lessons', '0002_alter_lesson_options_alter_lesson_course_and_more'),
        ('students', '0002_alter_student_options_alter_student_address_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grade',
            options={'ordering': ['-created_at'], 'verbose_name': 'Grade', 'verbose_name_plural': 'Grades'},
        ),
        migrations.AlterField(
            model_name='grade',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Comment'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='grade',
            field=models.PositiveSmallIntegerField(verbose_name='Grade'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='lessons.lesson', verbose_name='Lesson'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='students.student', verbose_name='Student'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='teacher',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'teacher'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='given_grades', to=settings.AUTH_USER_MODEL, verbose_name='Teacher'),
        ),
    ]
