# Generated by Django 6.0.6 on 2026-06-30 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='backupsetting',
            options={'verbose_name': 'Backup setting', 'verbose_name_plural': 'Backup settings'},
        ),
        migrations.AlterModelOptions(
            name='branch',
            options={'verbose_name': 'Branch', 'verbose_name_plural': 'Branches'},
        ),
        migrations.AlterModelOptions(
            name='lessontime',
            options={'ordering': ['start_time'], 'verbose_name': 'Lesson time', 'verbose_name_plural': 'Lesson times'},
        ),
        migrations.AlterModelOptions(
            name='organizationsetting',
            options={'verbose_name': 'Organization setting', 'verbose_name_plural': 'Organization settings'},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'verbose_name': 'Room', 'verbose_name_plural': 'Rooms'},
        ),
        migrations.AlterModelOptions(
            name='telegrambotsetting',
            options={'verbose_name': 'Telegram bot setting', 'verbose_name_plural': 'Telegram bot settings'},
        ),
        migrations.AlterField(
            model_name='backupsetting',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='backupsetting',
            name='is_enabled',
            field=models.BooleanField(default=True, verbose_name='Is enabled'),
        ),
        migrations.AlterField(
            model_name='backupsetting',
            name='last_backup_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last backup at'),
        ),
        migrations.AlterField(
            model_name='backupsetting',
            name='retention_days',
            field=models.PositiveIntegerField(default=30, verbose_name='Retention days'),
        ),
        migrations.AlterField(
            model_name='backupsetting',
            name='schedule',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='daily', max_length=10, verbose_name='Schedule'),
        ),
        migrations.AlterField(
            model_name='backupsetting',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='address',
            field=models.CharField(blank=True, max_length=500, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='lessontime',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='lessontime',
            name='end_time',
            field=models.TimeField(verbose_name='End time'),
        ),
        migrations.AlterField(
            model_name='lessontime',
            name='label',
            field=models.CharField(help_text='e.g. 1-пара, 2-пара', max_length=100, verbose_name='Label'),
        ),
        migrations.AlterField(
            model_name='lessontime',
            name='start_time',
            field=models.TimeField(verbose_name='Start time'),
        ),
        migrations.AlterField(
            model_name='lessontime',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='organizationsetting',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='organizationsetting',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='org/', verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='organizationsetting',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='organizationsetting',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='room',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='settings.branch', verbose_name='Branch'),
        ),
        migrations.AlterField(
            model_name='room',
            name='capacity',
            field=models.PositiveIntegerField(default=0, verbose_name='Capacity'),
        ),
        migrations.AlterField(
            model_name='room',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='room',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='smtpsetting',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='smtpsetting',
            name='from_email',
            field=models.EmailField(max_length=254, verbose_name='From email'),
        ),
        migrations.AlterField(
            model_name='smtpsetting',
            name='host',
            field=models.CharField(max_length=255, verbose_name='Host'),
        ),
        migrations.AlterField(
            model_name='smtpsetting',
            name='host_password',
            field=models.CharField(max_length=255, verbose_name='Host password'),
        ),
        migrations.AlterField(
            model_name='smtpsetting',
            name='host_user',
            field=models.CharField(max_length=255, verbose_name='Host user'),
        ),
        migrations.AlterField(
            model_name='smtpsetting',
            name='port',
            field=models.PositiveIntegerField(default=587, verbose_name='Port'),
        ),
        migrations.AlterField(
            model_name='smtpsetting',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
        migrations.AlterField(
            model_name='smtpsetting',
            name='use_tls',
            field=models.BooleanField(default=True, verbose_name='Use TLS'),
        ),
        migrations.AlterField(
            model_name='telegrambotsetting',
            name='bot_token',
            field=models.CharField(max_length=255, verbose_name='Bot token'),
        ),
        migrations.AlterField(
            model_name='telegrambotsetting',
            name='chat_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='Chat ID'),
        ),
        migrations.AlterField(
            model_name='telegrambotsetting',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='telegrambotsetting',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is active'),
        ),
        migrations.AlterField(
            model_name='telegrambotsetting',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated at'),
        ),
    ]
