# Generated by Django 6.0.6 on 2026-06-30 19:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notificationlog',
            options={'ordering': ['-created_at'], 'verbose_name': 'Notification log', 'verbose_name_plural': 'Notification logs'},
        ),
        migrations.AlterModelOptions(
            name='notificationsetting',
            options={'verbose_name': 'Notification setting', 'verbose_name_plural': 'Notification settings'},
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='body',
            field=models.TextField(verbose_name='Body'),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='channel',
            field=models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('telegram', 'Telegram')], max_length=10, verbose_name='Channel'),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='error_message',
            field=models.TextField(blank=True, verbose_name='Error message'),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='event_type',
            field=models.CharField(choices=[('user_created', 'User Created'), ('homework_assigned', 'Homework Assigned'), ('exam_scheduled', 'Exam Scheduled'), ('payment_reminder', 'Payment Reminder'), ('absent', 'Absent Notification'), ('custom', 'Custom')], max_length=20, verbose_name='Event type'),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Recipient'),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Sent at'),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='status',
            field=models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed'), ('pending', 'Pending')], default='pending', max_length=10, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='notificationlog',
            name='subject',
            field=models.CharField(max_length=200, verbose_name='Subject'),
        ),
        migrations.AlterField(
            model_name='notificationsetting',
            name='email_enabled',
            field=models.BooleanField(default=True, verbose_name='Email enabled'),
        ),
        migrations.AlterField(
            model_name='notificationsetting',
            name='sms_enabled',
            field=models.BooleanField(default=False, verbose_name='SMS enabled'),
        ),
        migrations.AlterField(
            model_name='notificationsetting',
            name='telegram_chat_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='Telegram chat ID'),
        ),
        migrations.AlterField(
            model_name='notificationsetting',
            name='telegram_enabled',
            field=models.BooleanField(default=False, verbose_name='Telegram enabled'),
        ),
        migrations.AlterField(
            model_name='notificationsetting',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_settings', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
